//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int taskid { get; set; }
        public bool done { get; set; }
        public string task1 { get; set; }
        public int userid { get; set; }
    }
}
